import type { PersonalIntelligenceSkillManifest } from "./skillRegistryTypes";
import { lucaFluidDesignReviewManifest } from "./lucaFluidDesignReviewManifest";

export const personalIntelligenceSkillRegistryFixtures: readonly PersonalIntelligenceSkillManifest[] = [
  lucaFluidDesignReviewManifest,
  {
    id: "writing-format-assistant",
    manifestId: "pi.writing-format-assistant",
    name: "Writing & Formatting Assistant",
    description: "Declares read-only structure, tone, and formatting support for user-provided text.",
    version: "1.0.0",
    category: "writing",
    permissions: ["text.read", "text.format.preview"],
    capabilities: ["text.formatting", "local.summarization"],
    requiredModels: [],
    requiredTools: [],
    requiredConnectors: [],
    memoryPolicy: { access: "none", read: [], write: [] },
    privacyZones: ["public", "private"],
    entrypointRef: "declarations/writing-format-assistant",
  },
  {
    id: "project-planning",
    manifestId: "pi.project-planning",
    name: "Project Planning",
    description: "Declares local planning, milestone organization, and review-ready next-step suggestions.",
    version: "1.0.0",
    category: "planning",
    permissions: ["planning.read_only"],
    capabilities: ["planning.read_only", "local.summarization"],
    requiredModels: [],
    requiredTools: [],
    requiredConnectors: [],
    memoryPolicy: { access: "none", read: [], write: [] },
    privacyZones: ["public", "project"],
    declarationRef: "declarations/project-planning",
  },
  {
    id: "memory-proposal-helper",
    manifestId: "pi.memory-proposal-helper",
    name: "Memory Proposal Helper",
    description: "Prepares a memory proposal for review without reading or writing the memory runtime.",
    version: "1.0.0",
    category: "memory",
    permissions: ["memory.proposal.request"],
    capabilities: ["memory.proposal"],
    requiredModels: [],
    requiredTools: [],
    requiredConnectors: [],
    memoryPolicy: { access: "proposal_only", read: [], write: [] },
    privacyZones: ["private", "project"],
    entrypointRef: "declarations/memory-proposal-helper",
  },
  {
    id: "dashboard-presentation-helper",
    manifestId: "pi.dashboard-presentation-helper",
    name: "Dashboard Presentation Helper",
    description: "Declares presentation-only dashboard summaries with no runtime mutation authority.",
    version: "1.0.0",
    category: "presentation",
    permissions: ["dashboard.presentation"],
    capabilities: ["dashboard.presentation"],
    requiredModels: ["text-model-declaration"],
    requiredTools: [],
    requiredConnectors: [],
    memoryPolicy: { access: "none", read: [], write: [] },
    privacyZones: ["public", "project"],
    entrypointRef: "declarations/dashboard-presentation-helper",
  },
  {
    id: "blocked-system-modifier",
    manifestId: "pi.blocked-system-modifier",
    name: "Blocked System Modifier",
    description: "Safety fixture declaring prohibited system modification capabilities without executable payloads.",
    version: "1.0.0",
    category: "system",
    permissions: ["shell.execution", "package.install"],
    capabilities: ["shell.execution", "package.install"],
    requiredModels: [],
    requiredTools: [],
    requiredConnectors: [],
    memoryPolicy: { access: "none", read: [], write: [] },
    privacyZones: ["public"],
    declarationRef: "blocked-declarations/system-modifier",
  },
  {
    id: "blocked-sensitive-controller",
    manifestId: "pi.blocked-sensitive-controller",
    name: "Blocked Sensitive Controller",
    description: "Safety fixture declaring prohibited sensitive-access and control categories only.",
    version: "1.0.0",
    category: "restricted",
    permissions: ["credential.access", "network.request", "device.control"],
    capabilities: ["credential.access", "network.request", "device.control"],
    requiredModels: [],
    requiredTools: [],
    requiredConnectors: ["restricted-connector-declaration"],
    memoryPolicy: { access: "none", read: [], write: [] },
    privacyZones: ["private"],
    declarationRef: "blocked-declarations/sensitive-controller",
  },
] as const;
