import React, { useCallback, useEffect, useState } from "react";
type Probe = { backend: string; available: boolean; isolated: boolean; reason: string; capabilities: string[] };
type Session = { sessionId: string; missionId: string; backend: string; status?: string; expiresAt?: string };
type SandboxBridge = { probe(): Promise<Probe>; list(): Promise<Session[]>; listSnapshots(sessionId?: string): Promise<unknown[]>; snapshot(sessionId: string): Promise<unknown>; cleanupExpired(): Promise<unknown[]>; destroy(sessionId: string): Promise<unknown> };
const bridge = () => (window as unknown as { luca?: { sandbox?: SandboxBridge } }).luca?.sandbox;

export const SandboxRuntimeSettingsPanel: React.FC = () => {
  const [probe, setProbe] = useState<Probe>(); const [sessions, setSessions] = useState<Session[]>([]); const [snapshots, setSnapshots] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const refresh = useCallback(async () => { const api = bridge(); if (!api) { setError("Sandbox controls are available in the LucaOS desktop app."); return; } try { const [nextProbe, nextSessions, nextSnapshots] = await Promise.all([api.probe(), api.list(), api.listSnapshots()]); setProbe(nextProbe); setSessions(nextSessions); setSnapshots(nextSnapshots.length); setError(""); } catch { setError("Sandbox status could not be loaded."); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const act = async (action: () => Promise<unknown>) => { setBusy(true); try { await action(); await refresh(); } catch { setError("Sandbox action failed safely."); } finally { setBusy(false); } };
  return <section aria-label="Sandbox runtime" className="space-y-3 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold text-white">Sandbox runtime</h3><p className="mt-1 text-xs text-white/55">Isolated execution only. Direct host fallback is disabled.</p></div><span className={`rounded-full border px-2 py-1 text-xs ${probe?.available && probe.isolated ? "border-emerald-300/25 text-emerald-100" : "border-amber-300/25 text-amber-100"}`}>{probe?.available && probe.isolated ? "Ready" : "Blocked"}</span></div>{probe && <p className="text-xs text-white/65">{probe.backend}: {probe.reason}</p>}{error && <p className="text-xs text-amber-100">{error}</p>}<div className="flex gap-4 text-xs text-white/55"><span>{sessions.length} sessions</span><span>{snapshots} snapshots</span></div>{sessions.map((session) => <div key={session.sessionId} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-white/10 p-3"><div><p className="text-xs text-white">{session.missionId}</p><p className="text-[11px] text-white/45">{session.backend} · {session.status || "running"}</p></div><div className="flex gap-2"><button disabled={busy} onClick={() => void act(() => bridge()!.snapshot(session.sessionId))} className="rounded-lg border border-white/15 px-2 py-1 text-xs text-white disabled:opacity-40">Snapshot</button><button disabled={busy} onClick={() => void act(() => bridge()!.destroy(session.sessionId))} className="rounded-lg border border-red-300/25 px-2 py-1 text-xs text-red-100 disabled:opacity-40">Destroy</button></div></div>)}<button disabled={busy || !bridge()} onClick={() => void act(() => bridge()!.cleanupExpired())} className="rounded-lg border border-white/15 px-3 py-1.5 text-xs text-white disabled:opacity-40">Clean expired sessions</button></section>;
};
export default SandboxRuntimeSettingsPanel;
