import type { SandboxFleetBackend } from "../../types/sandboxFleet"; import { sandboxBackendReleasePolicy } from "../../config/sandboxReleaseMatrix";
export interface SandboxCertificationEnvelope { evidence: { schemaVersion: 1; backend: string; host: { platform: string; arch: string; fingerprint: string }; imageDigests: string[]; checks: Record<string, boolean>; certifiedAt: string; runnerVersion: string }; signature: string; }
export interface SandboxReleaseGateInput { kind: SandboxFleetBackend["kind"]; platform: "windows" | "linux" | "macos"; installedAssets: string[]; availableFeatures: string[]; scannerAvailable: boolean; certification?: SandboxCertificationEnvelope; }
export interface SandboxReleaseDecision { status: "ready" | "blocked"; tier: "stable" | "preview" | "unsupported"; blockers: string[]; certificationFingerprint?: string; hostFallbackAllowed: false; }
const requiredChecks = ["probeIsolated", "createDestroy", "commandIsolation", "networkPolicy", "artifactIntegrity", "snapshotCleanup", "crashRecovery"];
export class SandboxReleaseGate {
  constructor(private readonly certificationPublicKey: Uint8Array, private readonly maxEvidenceAgeMs = 90 * 24 * 60 * 60 * 1000, private readonly now = () => Date.now()) {}
  async evaluate(input: SandboxReleaseGateInput): Promise<SandboxReleaseDecision> { const policy = sandboxBackendReleasePolicy(input.kind); if (!policy || !policy.hosts.includes(input.platform)) return { status: "blocked", tier: "unsupported", blockers: ["Backend is unsupported on this host."], hostFallbackAllowed: false }; const blockers = [...policy.requiredAssets.filter((id) => !input.installedAssets.includes(id)).map((id) => `Verified asset missing: ${id}.`), ...policy.requiredFeatures.filter((id) => !input.availableFeatures.includes(id)).map((id) => `Host feature missing: ${id}.`)]; if (!input.scannerAvailable) blockers.push("Artifact scanner is unavailable."); const certification = input.certification; let fingerprint: string | undefined; if (!certification) blockers.push("Signed hardware certification is missing."); else { const evidenceBytes = new TextEncoder().encode(JSON.stringify(certification.evidence)); const key = await crypto.subtle.importKey("raw", this.certificationPublicKey as BufferSource, { name: "Ed25519" }, false, ["verify"]); const valid = await crypto.subtle.verify("Ed25519", key, Uint8Array.from(atob(certification.signature), (c) => c.charCodeAt(0)), evidenceBytes); if (!valid || certification.evidence.backend !== input.kind || requiredChecks.some((check) => certification.evidence.checks[check] !== true)) blockers.push("Hardware certification evidence is invalid."); else if (this.now() - Date.parse(certification.evidence.certifiedAt) > this.maxEvidenceAgeMs) blockers.push("Hardware certification evidence has expired."); else fingerprint = certification.evidence.host.fingerprint; } if (policy.tier === "preview") blockers.push("Backend is preview and cannot ship as stable."); return { status: blockers.length ? "blocked" : "ready", tier: policy.tier, blockers, certificationFingerprint: fingerprint, hostFallbackAllowed: false }; }
}
