/**
 * The two-dimensional identity gate: what the orb's outline actually is.
 *
 * V1 of this file was hand-typed from a screenshot. Every path was a guess that
 * looked plausible at 40% opacity, and because nothing compared them to the
 * master, the guesses could not be told apart from measurements. V2 keeps the
 * same review surface and marks each layer with where its numbers came from.
 *
 * The outer silhouette is now measured — generated by
 * `scripts/orb-trace-master.mjs` from the frozen master and imported here rather
 * than transcribed. The four interior layers are still hand-authored and are
 * labelled as such, because they were drawn against the V1 silhouette and no
 * extraction has confirmed them yet. Do not approve them as if they were traced.
 */

import { HERO_CONTOUR_V1_LANDMARKS, HERO_CONTOUR_V1_PATH } from '../trace/hero-contour.v1';

export type OrbBlueprintLayerId =
  | 'outer-silhouette'
  | 'crown-edge'
  | 'lower-fold'
  | 'right-return'
  | 'inner-mass';

/**
 * Where a layer's control points came from.
 *
 * `measured` means generated from the master by the trace script and
 * regenerable. `hand-authored` means someone drew it by eye; it may be right,
 * but nothing has checked it.
 */
export type OrbBlueprintProvenance = 'measured' | 'hand-authored';

export interface OrbBlueprintLayer {
  readonly id: OrbBlueprintLayerId;
  readonly label: string;
  readonly path: string;
  readonly closed: boolean;
  readonly provenance: OrbBlueprintProvenance;
}

export interface OrbBlueprintLandmark {
  readonly id: string;
  readonly x: number;
  readonly y: number;
  readonly provenance: OrbBlueprintProvenance;
}

const [crownApexX, crownApexY] = HERO_CONTOUR_V1_LANDMARKS.crownApex;
const [rightmostX, rightmostY] = HERO_CONTOUR_V1_LANDMARKS.rightmostReturn;
const [lowerFoldX, lowerFoldY] = HERO_CONTOUR_V1_LANDMARKS.lowerFoldApex;
const [leftmostX, leftmostY] = HERO_CONTOUR_V1_LANDMARKS.leftmostMembrane;

/**
 * TRACED SILHOUETTE V2.
 *
 * Paths are in the frozen 360 x 360 hero crop, so a coordinate here is directly
 * comparable to the pixel tolerances in `design-spec/HeroAssembly.v3.md`.
 */
export const LUCA_HERO_BLUEPRINT_V1 = Object.freeze({
  id: 'luca-living-orb/hero-blueprint',
  version: 2,
  viewBox: Object.freeze([0, 0, 360, 360] as const),
  layers: Object.freeze<readonly OrbBlueprintLayer[]>([
    Object.freeze({
      id: 'outer-silhouette',
      label: 'Outer membrane silhouette (traced)',
      closed: true,
      provenance: 'measured',
      path: HERO_CONTOUR_V1_PATH,
    }),
    Object.freeze({
      id: 'crown-edge',
      label: 'Upper crown overlap (drawn by eye)',
      closed: false,
      provenance: 'hand-authored',
      path: 'M 61 155 C 68 132 82 107 101 89 C 119 72 141 64 163 64 C 187 64 205 71 224 81 C 245 91 263 91 281 101 C 294 108 304 118 311 130',
    }),
    Object.freeze({
      id: 'lower-fold',
      label: 'Lower forward fold (drawn by eye)',
      closed: false,
      provenance: 'hand-authored',
      path: 'M 56 200 C 61 220 75 235 96 245 C 116 255 130 258 146 270 C 163 282 184 289 207 287 C 235 285 256 273 270 253 C 279 241 285 225 295 211',
    }),
    Object.freeze({
      id: 'right-return',
      label: 'Right membrane return (drawn by eye)',
      closed: false,
      provenance: 'hand-authored',
      path: 'M 280 101 C 300 109 314 126 317 145 C 321 165 313 184 302 201 C 290 220 281 239 268 255',
    }),
    Object.freeze({
      id: 'inner-mass',
      label: 'Suspended inner mass (drawn by eye)',
      closed: true,
      provenance: 'hand-authored',
      path: 'M 171 78 C 202 76 224 87 249 96 C 275 103 299 113 307 134 C 317 158 304 181 289 201 C 275 221 270 244 251 260 C 232 276 207 281 183 276 C 159 272 144 261 124 253 C 101 244 78 232 68 212 C 57 189 64 166 78 145 C 92 123 105 101 128 88 C 141 81 156 78 171 78 Z',
    }),
  ]),
  landmarks: Object.freeze<readonly OrbBlueprintLandmark[]>([
    Object.freeze({ id: 'crown-apex', x: crownApexX, y: crownApexY, provenance: 'measured' }),
    Object.freeze({ id: 'rightmost-return', x: rightmostX, y: rightmostY, provenance: 'measured' }),
    Object.freeze({ id: 'lower-fold-apex', x: lowerFoldX, y: lowerFoldY, provenance: 'measured' }),
    Object.freeze({ id: 'leftmost-membrane', x: leftmostX, y: leftmostY, provenance: 'measured' }),
    Object.freeze({ id: 'inner-mass-focus', x: 177, y: 179, provenance: 'hand-authored' }),
  ]),
});
