const { execFile: nodeExecFile } = require('child_process'); const { promisify } = require('util'); const fs = require('fs'); const path = require('path');
function createAppleVirtualizationSandboxAdapter({ execFile = promisify(nodeExecFile), fsApi = fs, platform = process.platform, helperPath, imagePath, stateRoot } = {}) {
    for (const [name, value] of Object.entries({ helperPath, imagePath, stateRoot })) if (!value || !path.isAbsolute(value)) throw new Error(`Apple virtualization ${name} must be absolute.`);
    return { kind: 'apple_virtualization',
        async probe() { if (platform !== 'darwin') return { backend: 'apple_virtualization', available: false, isolated: false, reason: 'Apple Virtualization requires macOS.', capabilities: [] }; if (!fsApi.existsSync(helperPath) || !fsApi.existsSync(imagePath)) return { backend: 'apple_virtualization', available: false, isolated: false, reason: 'Signed virtualization helper or managed guest image is missing.', capabilities: [] }; try { const result = await execFile(helperPath, ['probe', '--json'], { timeout: 10_000 }); const proof = JSON.parse(String(result.stdout)); if (proof.framework !== 'Virtualization.framework' || proof.entitled !== true) throw new Error(); return { backend: 'apple_virtualization', available: true, isolated: true, reason: 'Apple Virtualization Framework is available.', capabilities: ['terminal', 'workspace_read', 'workspace_write', 'network'] }; } catch { return { backend: 'apple_virtualization', available: false, isolated: false, reason: 'Virtualization helper attestation failed.', capabilities: [] }; } },
        async create({ sessionId, networkEnabled = false }) { if (!/^[a-f0-9-]{36}$/.test(sessionId)) throw new Error('Invalid Apple VM session id.'); const sessionRoot = path.join(stateRoot, sessionId); fsApi.mkdirSync(sessionRoot, { recursive: true }); await execFile(helperPath, ['create', '--session', sessionId, '--image', imagePath, '--state', sessionRoot, '--network', networkEnabled ? 'nat' : 'none'], { timeout: 120_000 }); return { backend: 'apple_virtualization', sessionId, sessionRoot, networkEnabled }; },
        async execute(runtime, command) { const result = await execFile(helperPath, ['exec', '--session', runtime.sessionId, '--', command.executable, ...command.args], { timeout: command.timeoutMs, maxBuffer: 1024 * 1024 }); return { stdout: String(result.stdout || ''), stderr: String(result.stderr || ''), exitCode: 0 }; },
        async destroy(runtime) { try { await execFile(helperPath, ['destroy', '--session', runtime.sessionId], { timeout: 30_000 }); } finally { fsApi.rmSync(runtime.sessionRoot, { recursive: true, force: true }); } }
    };
}
module.exports = { createAppleVirtualizationSandboxAdapter };
