const { execFile: nodeExecFile } = require('child_process'); const { promisify } = require('util'); const fs = require('fs'); const path = require('path');
function createHyperVSandboxAdapter({ execFile = promisify(nodeExecFile), fsApi = fs, platform = process.platform, imagePath, stateRoot } = {}) {
    for (const [name, value] of Object.entries({ imagePath, stateRoot })) if (!value || !path.isAbsolute(value)) throw new Error(`Hyper-V ${name} must be absolute.`);
    const ps = (script, timeout = 30_000) => execFile('powershell.exe', ['-NoLogo', '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'RemoteSigned', '-Command', script], { windowsHide: true, timeout, maxBuffer: 1024 * 1024 });
    return { kind: 'hyperv',
        async probe() { if (platform !== 'win32') return { backend: 'hyperv', available: false, isolated: false, reason: 'Hyper-V requires Windows.', capabilities: [] }; if (!fsApi.existsSync(imagePath)) return { backend: 'hyperv', available: false, isolated: false, reason: 'Managed Hyper-V guest image is missing.', capabilities: [] }; try { const result = await ps("$f=Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All; if($f.State -ne 'Enabled'){exit 3}; 'enabled'"); return String(result.stdout).includes('enabled') ? { backend: 'hyperv', available: true, isolated: true, reason: 'Hyper-V is enabled with a managed image.', capabilities: ['terminal', 'workspace_read', 'workspace_write', 'network'] } : { backend: 'hyperv', available: false, isolated: false, reason: 'Hyper-V feature is disabled.', capabilities: [] }; } catch { return { backend: 'hyperv', available: false, isolated: false, reason: 'Hyper-V feature or administrative access is unavailable.', capabilities: [] }; } },
        async create({ sessionId, networkEnabled = false }) { if (!/^[a-f0-9-]{36}$/.test(sessionId)) throw new Error('Invalid Hyper-V session id.'); const vmName = `LucaOS-Sandbox-${sessionId}`; const sessionRoot = path.join(stateRoot, sessionId); fsApi.mkdirSync(sessionRoot, { recursive: true }); const disk = path.join(sessionRoot, 'guest.vhdx'); fsApi.copyFileSync(imagePath, disk); await ps(`New-VM -Name '${vmName}' -Generation 2 -MemoryStartupBytes 2GB -VHDPath '${disk.replaceAll("'", "''")}' | Out-Null; Set-VM -Name '${vmName}' -AutomaticCheckpointsEnabled $false; Start-VM -Name '${vmName}'`, 120_000); return { backend: 'hyperv', sessionId, vmName, sessionRoot, networkEnabled }; },
        async execute(runtime, command) { const payload = Buffer.from(JSON.stringify({ executable: command.executable, args: command.args })).toString('base64'); const result = await ps(`Invoke-Command -VMName '${runtime.vmName}' -ScriptBlock { param($p) $c=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($p))|ConvertFrom-Json; & $c.executable @($c.args) } -ArgumentList '${payload}'`, command.timeoutMs); return { stdout: String(result.stdout || ''), stderr: String(result.stderr || ''), exitCode: 0 }; },
        async destroy(runtime) { try { await ps(`Stop-VM -Name '${runtime.vmName}' -TurnOff -Force -ErrorAction SilentlyContinue; Remove-VM -Name '${runtime.vmName}' -Force -ErrorAction SilentlyContinue`); } finally { fsApi.rmSync(runtime.sessionRoot, { recursive: true, force: true }); } }
    };
}
module.exports = { createHyperVSandboxAdapter };
